group:
  radio:
    name: Radio
    entities:
    - input_select.radio_station
    - input_select.chromecast_radio
    - script.radio
    - input_number.volume_radio

input_select:
  radio_station:
    name: 'Select Radio Station:'
    options:
      - RTE One
      - RTE RnaG
    initial: RTE One
    icon: mdi:radio

  chromecast_radio:
    name: 'Select Speakers:'
    options:
      - Bedroom
      - Living Room
      - All
    initial: All
    icon: mdi:speaker-wireless

input_number:
  volume_radio:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05

automation:
  - alias: Set Chromecast Radio Volume
    trigger:
      platform: state
      entity_id: input_number.volume_radio
    action:
      service: media_player.volume_set
      data_template:
        entity_id: >
          {% if is_state("input_select.chromecast_radio", "Bedroom") %} media_player.bedroom_clock
          {% elif is_state("input_select.chromecast_radio", "Living Room") %} media_player.hall_speaker
          {% elif is_state("input_select.chromecast_radio", "All") %} media_player.speakers
          {% endif %}
        volume_level: '{{  states.input_number.volume_radio.state  }}'

script:
  radio:
    alias: Play Radio on Chromecast Audio
    sequence:
    - service: media_player.volume_set
      data_template:
        entity_id: >
          {% if is_state("input_select.chromecast_radio", "Bedroom") %} media_player.bedroom_clock
          {% elif is_state("input_select.chromecast_radio", "Living Room") %} media_player.hall_speaker
          {% elif is_state("input_select.chromecast_radio", "All") %} media_player.speakers
          {% endif %}
        volume_level: '{{  states.input_number.volume_radio.state  }}'
    - service: media_player.play_media
      data_template:
        entity_id: >
          {% if is_state("input_select.chromecast_radio", "Bedroom") %} media_player.bedroom_clock
          {% elif is_state("input_select.chromecast_radio", "Living Room") %} media_player.hall_speaker
          {% elif is_state("input_select.chromecast_radio", "All") %} media_player.speakers
          {% endif %}
        media_content_id: >
          {% if is_state("input_select.radio_station", "RTE One") %} http://icecast2.rte.ie/radio1
          {% elif is_state("input_select.radio_station", "RTE RnaG") %} http://icecast1.rte.ie/rnag
          {% endif %}
        media_content_type: 'audio/mp4'